/*
 * This the frame class that holds the physical objects within the Calculator
 * Drew White 92017830
 * 3/4/17
 */
package calculatorproject;

import javax.swing.JFrame;
import java.awt.Font;

/**
 *
 * @author 92017830
 */
public class CalculatorFrame extends javax.swing.JFrame {

    /**
     * Creates new form CalculatorFrame
     */
    public CalculatorFrame() {
        initComponents();
        pnlScientific.setVisible(false);

    }

    public void setBasicSize() {
        this.setSize(325, 450);
    }

    public void setExtendedSize() {
        this.setSize(500, 450);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pneMessages = new javax.swing.JOptionPane();
        bgrDegRad = new javax.swing.ButtonGroup();
        bgrPlainBold = new javax.swing.ButtonGroup();
        bgrRounding = new javax.swing.ButtonGroup();
        txtDisplay = new javax.swing.JTextField();
        btnOne = new javax.swing.JButton();
        btnTwo = new javax.swing.JButton();
        btnThree = new javax.swing.JButton();
        btnFour = new javax.swing.JButton();
        btnFive = new javax.swing.JButton();
        btnSix = new javax.swing.JButton();
        btnSeven = new javax.swing.JButton();
        btnEight = new javax.swing.JButton();
        btnZero = new javax.swing.JButton();
        btnNine = new javax.swing.JButton();
        btnFraction = new javax.swing.JButton();
        btnPosNeg = new javax.swing.JButton();
        btnToThePowerOf = new javax.swing.JButton();
        btnDivide = new javax.swing.JButton();
        btnSubtract = new javax.swing.JButton();
        btnMultiply = new javax.swing.JButton();
        btnPlus = new javax.swing.JButton();
        btnEquals = new javax.swing.JButton();
        btnPoint = new javax.swing.JButton();
        btnFactorial = new javax.swing.JButton();
        btnClearAll = new javax.swing.JButton();
        btnClearEntry = new javax.swing.JButton();
        pnlScientific = new javax.swing.JPanel();
        radDegrees = new javax.swing.JRadioButton();
        radRadians = new javax.swing.JRadioButton();
        btnPi = new javax.swing.JButton();
        btnSin = new javax.swing.JButton();
        btnE = new javax.swing.JButton();
        btnCos = new javax.swing.JButton();
        btnAcos = new javax.swing.JButton();
        btnAsin = new javax.swing.JButton();
        btnTan = new javax.swing.JButton();
        btnAtan = new javax.swing.JButton();
        mnuMenuBar = new javax.swing.JMenuBar();
        mnuView = new javax.swing.JMenu();
        radBasic = new javax.swing.JRadioButtonMenuItem();
        radExtended = new javax.swing.JRadioButtonMenuItem();
        mnuFont = new javax.swing.JMenu();
        radPlain = new javax.swing.JRadioButtonMenuItem();
        radBold = new javax.swing.JRadioButtonMenuItem();
        mnuRound = new javax.swing.JMenu();
        radZero = new javax.swing.JRadioButtonMenuItem();
        radOne = new javax.swing.JRadioButtonMenuItem();
        radTwo = new javax.swing.JRadioButtonMenuItem();
        radThree = new javax.swing.JRadioButtonMenuItem();
        radFour = new javax.swing.JRadioButtonMenuItem();
        radFive = new javax.swing.JRadioButtonMenuItem();
        radSix = new javax.swing.JRadioButtonMenuItem();
        radSeven = new javax.swing.JRadioButtonMenuItem();
        radEight = new javax.swing.JRadioButtonMenuItem();
        radNine = new javax.swing.JRadioButtonMenuItem();
        mnuHelp = new javax.swing.JMenu();
        mnuAbout = new javax.swing.JMenuItem();
        mnuHotKeys = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Project Calculator");

        txtDisplay.setEditable(false);
        txtDisplay.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtDisplay.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtDisplay.setText("0.0");

        btnOne.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnOne.setText("1");
        btnOne.setMaximumSize(new java.awt.Dimension(50, 50));
        btnOne.setMinimumSize(new java.awt.Dimension(50, 50));
        btnOne.setPreferredSize(new java.awt.Dimension(50, 50));
        btnOne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOneActionPerformed(evt);
            }
        });

        btnTwo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnTwo.setText("2");
        btnTwo.setMaximumSize(new java.awt.Dimension(50, 50));
        btnTwo.setMinimumSize(new java.awt.Dimension(50, 50));
        btnTwo.setPreferredSize(new java.awt.Dimension(50, 50));
        btnTwo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTwoActionPerformed(evt);
            }
        });

        btnThree.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnThree.setText("3");
        btnThree.setMaximumSize(new java.awt.Dimension(50, 50));
        btnThree.setMinimumSize(new java.awt.Dimension(50, 50));
        btnThree.setPreferredSize(new java.awt.Dimension(50, 50));
        btnThree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThreeActionPerformed(evt);
            }
        });

        btnFour.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnFour.setText("4");
        btnFour.setMaximumSize(new java.awt.Dimension(50, 50));
        btnFour.setMinimumSize(new java.awt.Dimension(50, 50));
        btnFour.setPreferredSize(new java.awt.Dimension(50, 50));
        btnFour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFourActionPerformed(evt);
            }
        });

        btnFive.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnFive.setText("5");
        btnFive.setMaximumSize(new java.awt.Dimension(50, 50));
        btnFive.setMinimumSize(new java.awt.Dimension(50, 50));
        btnFive.setPreferredSize(new java.awt.Dimension(50, 50));
        btnFive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiveActionPerformed(evt);
            }
        });

        btnSix.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnSix.setText("6");
        btnSix.setMaximumSize(new java.awt.Dimension(50, 50));
        btnSix.setMinimumSize(new java.awt.Dimension(50, 50));
        btnSix.setPreferredSize(new java.awt.Dimension(50, 50));
        btnSix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSixActionPerformed(evt);
            }
        });

        btnSeven.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnSeven.setText("7");
        btnSeven.setMaximumSize(new java.awt.Dimension(50, 50));
        btnSeven.setMinimumSize(new java.awt.Dimension(50, 50));
        btnSeven.setPreferredSize(new java.awt.Dimension(50, 50));
        btnSeven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSevenActionPerformed(evt);
            }
        });

        btnEight.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnEight.setText("8");
        btnEight.setMaximumSize(new java.awt.Dimension(50, 50));
        btnEight.setMinimumSize(new java.awt.Dimension(50, 50));
        btnEight.setPreferredSize(new java.awt.Dimension(50, 50));
        btnEight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEightActionPerformed(evt);
            }
        });

        btnZero.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnZero.setText("0");
        btnZero.setMaximumSize(new java.awt.Dimension(50, 50));
        btnZero.setMinimumSize(new java.awt.Dimension(50, 50));
        btnZero.setPreferredSize(new java.awt.Dimension(50, 50));
        btnZero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZeroActionPerformed(evt);
            }
        });

        btnNine.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnNine.setText("9");
        btnNine.setMaximumSize(new java.awt.Dimension(50, 50));
        btnNine.setMinimumSize(new java.awt.Dimension(50, 50));
        btnNine.setPreferredSize(new java.awt.Dimension(50, 50));
        btnNine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNineActionPerformed(evt);
            }
        });

        btnFraction.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnFraction.setText("1/x");
        btnFraction.setMaximumSize(new java.awt.Dimension(50, 50));
        btnFraction.setMinimumSize(new java.awt.Dimension(50, 50));
        btnFraction.setPreferredSize(new java.awt.Dimension(50, 50));
        btnFraction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFractionActionPerformed(evt);
            }
        });

        btnPosNeg.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnPosNeg.setText("+/-");
        btnPosNeg.setMaximumSize(new java.awt.Dimension(50, 50));
        btnPosNeg.setMinimumSize(new java.awt.Dimension(50, 50));
        btnPosNeg.setPreferredSize(new java.awt.Dimension(50, 50));
        btnPosNeg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPosNegActionPerformed(evt);
            }
        });

        btnToThePowerOf.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnToThePowerOf.setText("x^y");
        btnToThePowerOf.setMaximumSize(new java.awt.Dimension(50, 50));
        btnToThePowerOf.setMinimumSize(new java.awt.Dimension(50, 50));
        btnToThePowerOf.setPreferredSize(new java.awt.Dimension(50, 50));
        btnToThePowerOf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnToThePowerOfActionPerformed(evt);
            }
        });

        btnDivide.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnDivide.setText("/");
        btnDivide.setMaximumSize(new java.awt.Dimension(50, 50));
        btnDivide.setMinimumSize(new java.awt.Dimension(50, 50));
        btnDivide.setPreferredSize(new java.awt.Dimension(50, 50));
        btnDivide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDivideActionPerformed(evt);
            }
        });

        btnSubtract.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnSubtract.setText("-");
        btnSubtract.setMaximumSize(new java.awt.Dimension(50, 50));
        btnSubtract.setMinimumSize(new java.awt.Dimension(50, 50));
        btnSubtract.setPreferredSize(new java.awt.Dimension(50, 50));
        btnSubtract.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubtractActionPerformed(evt);
            }
        });

        btnMultiply.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnMultiply.setText("*");
        btnMultiply.setMaximumSize(new java.awt.Dimension(50, 50));
        btnMultiply.setMinimumSize(new java.awt.Dimension(50, 50));
        btnMultiply.setPreferredSize(new java.awt.Dimension(50, 50));
        btnMultiply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMultiplyActionPerformed(evt);
            }
        });

        btnPlus.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnPlus.setText("+");
        btnPlus.setMaximumSize(new java.awt.Dimension(50, 50));
        btnPlus.setMinimumSize(new java.awt.Dimension(50, 50));
        btnPlus.setPreferredSize(new java.awt.Dimension(50, 50));
        btnPlus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlusActionPerformed(evt);
            }
        });

        btnEquals.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnEquals.setText("=");
        btnEquals.setMaximumSize(new java.awt.Dimension(50, 50));
        btnEquals.setMinimumSize(new java.awt.Dimension(50, 50));
        btnEquals.setPreferredSize(new java.awt.Dimension(50, 50));
        btnEquals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEqualsActionPerformed(evt);
            }
        });

        btnPoint.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnPoint.setText(".");
        btnPoint.setMaximumSize(new java.awt.Dimension(50, 50));
        btnPoint.setMinimumSize(new java.awt.Dimension(50, 50));
        btnPoint.setPreferredSize(new java.awt.Dimension(50, 50));
        btnPoint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPointActionPerformed(evt);
            }
        });

        btnFactorial.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnFactorial.setText("x!");
        btnFactorial.setMaximumSize(new java.awt.Dimension(50, 50));
        btnFactorial.setMinimumSize(new java.awt.Dimension(50, 50));
        btnFactorial.setPreferredSize(new java.awt.Dimension(50, 50));
        btnFactorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFactorialActionPerformed(evt);
            }
        });

        btnClearAll.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnClearAll.setText("CA");
        btnClearAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearAllActionPerformed(evt);
            }
        });

        btnClearEntry.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnClearEntry.setText("CE");
        btnClearEntry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearEntryActionPerformed(evt);
            }
        });

        bgrDegRad.add(radDegrees);
        radDegrees.setSelected(true);
        radDegrees.setText("Degrees");

        bgrDegRad.add(radRadians);
        radRadians.setText("Radians");

        btnPi.setText("PI");
        btnPi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPiActionPerformed(evt);
            }
        });

        btnSin.setText("sin");
        btnSin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSinActionPerformed(evt);
            }
        });

        btnE.setText("E");
        btnE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEActionPerformed(evt);
            }
        });

        btnCos.setText("cos");
        btnCos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCosActionPerformed(evt);
            }
        });

        btnAcos.setText("acos");
        btnAcos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcosActionPerformed(evt);
            }
        });

        btnAsin.setText("asin");
        btnAsin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsinActionPerformed(evt);
            }
        });

        btnTan.setText("tan");
        btnTan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTanActionPerformed(evt);
            }
        });

        btnAtan.setText("atan");
        btnAtan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlScientificLayout = new javax.swing.GroupLayout(pnlScientific);
        pnlScientific.setLayout(pnlScientificLayout);
        pnlScientificLayout.setHorizontalGroup(
            pnlScientificLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlScientificLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(radDegrees)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radRadians)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlScientificLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlScientificLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlScientificLayout.createSequentialGroup()
                        .addComponent(btnPi, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnE, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlScientificLayout.createSequentialGroup()
                        .addComponent(btnTan, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAtan, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlScientificLayout.createSequentialGroup()
                        .addComponent(btnCos, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAcos, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlScientificLayout.createSequentialGroup()
                        .addComponent(btnSin, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAsin, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pnlScientificLayout.setVerticalGroup(
            pnlScientificLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlScientificLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlScientificLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radDegrees)
                    .addComponent(radRadians))
                .addGap(18, 18, 18)
                .addGroup(pnlScientificLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSin, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAsin, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlScientificLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAcos, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlScientificLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTan, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAtan, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlScientificLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnE, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPi, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        mnuView.setMnemonic('V');
        mnuView.setText("View");
        mnuView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuViewActionPerformed(evt);
            }
        });

        radBasic.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, 0));
        bgrPlainBold.add(radBasic);
        radBasic.setSelected(true);
        radBasic.setText("Basic");
        radBasic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radBasicActionPerformed(evt);
            }
        });
        mnuView.add(radBasic);

        radExtended.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, 0));
        bgrPlainBold.add(radExtended);
        radExtended.setText("Extended");
        radExtended.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radExtendedActionPerformed(evt);
            }
        });
        mnuView.add(radExtended);

        mnuMenuBar.add(mnuView);

        mnuFont.setMnemonic('F');
        mnuFont.setText("Font");

        radPlain.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        bgrPlainBold.add(radPlain);
        radPlain.setText("Plain");
        radPlain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radPlainActionPerformed(evt);
            }
        });
        mnuFont.add(radPlain);

        radBold.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_MASK));
        bgrPlainBold.add(radBold);
        radBold.setText("Bold");
        radBold.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radBoldActionPerformed(evt);
            }
        });
        mnuFont.add(radBold);

        mnuMenuBar.add(mnuFont);

        mnuRound.setMnemonic('R');
        mnuRound.setText("Round");

        bgrRounding.add(radZero);
        radZero.setText("0");
        radZero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radZeroActionPerformed(evt);
            }
        });
        mnuRound.add(radZero);

        bgrRounding.add(radOne);
        radOne.setText("1");
        radOne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radOneActionPerformed(evt);
            }
        });
        mnuRound.add(radOne);

        bgrRounding.add(radTwo);
        radTwo.setText("2");
        radTwo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radTwoActionPerformed(evt);
            }
        });
        mnuRound.add(radTwo);

        bgrRounding.add(radThree);
        radThree.setText("3");
        radThree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radThreeActionPerformed(evt);
            }
        });
        mnuRound.add(radThree);

        bgrRounding.add(radFour);
        radFour.setText("4");
        radFour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radFourActionPerformed(evt);
            }
        });
        mnuRound.add(radFour);

        bgrRounding.add(radFive);
        radFive.setText("5");
        radFive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radFiveActionPerformed(evt);
            }
        });
        mnuRound.add(radFive);

        bgrRounding.add(radSix);
        radSix.setText("6");
        radSix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radSixActionPerformed(evt);
            }
        });
        mnuRound.add(radSix);

        bgrRounding.add(radSeven);
        radSeven.setText("7");
        radSeven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radSevenActionPerformed(evt);
            }
        });
        mnuRound.add(radSeven);

        bgrRounding.add(radEight);
        radEight.setText("8");
        radEight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radEightActionPerformed(evt);
            }
        });
        mnuRound.add(radEight);

        bgrRounding.add(radNine);
        radNine.setText("9");
        radNine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radNineActionPerformed(evt);
            }
        });
        mnuRound.add(radNine);

        mnuMenuBar.add(mnuRound);

        mnuHelp.setMnemonic('H');
        mnuHelp.setText("Help");

        mnuAbout.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, 0));
        mnuAbout.setText("About");
        mnuAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAboutActionPerformed(evt);
            }
        });
        mnuHelp.add(mnuAbout);

        mnuHotKeys.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_K, 0));
        mnuHotKeys.setText("Hot Keys");
        mnuHotKeys.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuHotKeysActionPerformed(evt);
            }
        });
        mnuHelp.add(mnuHotKeys);

        mnuMenuBar.add(mnuHelp);

        setJMenuBar(mnuMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtDisplay)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnSeven, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnZero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnFour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnEight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnNine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnPlus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnPoint, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnEquals, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnSubtract, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnFive, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnSix, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnDivide, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnPosNeg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnToThePowerOf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnFactorial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnClearEntry, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnClearAll, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(56, 56, 56)))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnOne, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(6, 6, 6)
                            .addComponent(btnTwo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnThree, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnMultiply, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnFraction, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(pnlScientific, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnClearAll, btnClearEntry});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlScientific, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnOne, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnTwo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnThree, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnMultiply, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnFraction, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnFour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnFive, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSix, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnDivide, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnToThePowerOf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSeven, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnNine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnPlus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnPosNeg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnZero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnPoint, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEquals, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSubtract, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnFactorial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnClearEntry, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnClearAll, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(198, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnClearAll, btnClearEntry});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Displays the full extended calculator
    private void radExtendedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radExtendedActionPerformed
        if (radExtended.isSelected()) {
            pnlScientific.setVisible(true);
            setExtendedSize();
        }
    }//GEN-LAST:event_radExtendedActionPerformed

    private void mnuViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuViewActionPerformed
        //Does nothing. Just a click in the wrong place.
    }//GEN-LAST:event_mnuViewActionPerformed

    //Returns the calculator to the standard basic version
    private void radBasicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radBasicActionPerformed
        if (radBasic.isSelected()) {
            pnlScientific.setVisible(false);
            setBasicSize();

        }
    }//GEN-LAST:event_radBasicActionPerformed

    //Adds one to the display when 1 button pushed
    private void btnOneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOneActionPerformed
        if (Calculations.numComplete == true) {
            txtDisplay.setText("1");

        } else {
            txtDisplay.setText(txtDisplay.getText() + "1");
        }
        Calculations.numComplete = false;
    }//GEN-LAST:event_btnOneActionPerformed

    //Adds 2 to the display when the 2 button is pushed
    private void btnTwoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTwoActionPerformed
        if (Calculations.numComplete == true) {
            txtDisplay.setText("2");
        } else {
            txtDisplay.setText(txtDisplay.getText() + "2");
        }
        Calculations.numComplete = false;
    }//GEN-LAST:event_btnTwoActionPerformed

    //Adds 3 to the display
    private void btnThreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThreeActionPerformed
        if (Calculations.numComplete == true) {
            txtDisplay.setText("3");
        } else {
            txtDisplay.setText(txtDisplay.getText() + "3");
        }
        Calculations.numComplete = false;
    }//GEN-LAST:event_btnThreeActionPerformed

    //Adds 4 to the display
    private void btnFourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFourActionPerformed
        if (Calculations.numComplete == true) {
            txtDisplay.setText("4");
        } else {
            txtDisplay.setText(txtDisplay.getText() + "4");
        }
        Calculations.numComplete = false;
    }//GEN-LAST:event_btnFourActionPerformed

    //Adds 5 to the display
    private void btnFiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiveActionPerformed
        if (Calculations.numComplete == true) {
            txtDisplay.setText("5");
        } else {
            txtDisplay.setText(txtDisplay.getText() + "5");
        }
        Calculations.numComplete = false;
    }//GEN-LAST:event_btnFiveActionPerformed

    //Adds 6 to the display
    private void btnSixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSixActionPerformed
        if (Calculations.numComplete == true) {
            txtDisplay.setText("6");
        } else {
            txtDisplay.setText(txtDisplay.getText() + "6");
        }
        Calculations.numComplete = false;
    }//GEN-LAST:event_btnSixActionPerformed

    //Adds 7 to the display
    private void btnSevenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSevenActionPerformed
        if (Calculations.numComplete == true) {
            txtDisplay.setText("7");

        } else {
            txtDisplay.setText(txtDisplay.getText() + "7");
        }
        Calculations.numComplete = false;
    }//GEN-LAST:event_btnSevenActionPerformed

    //Adds 8 to the display
    private void btnEightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEightActionPerformed
        if (Calculations.numComplete == true) {
            txtDisplay.setText("8");
        } else {
            txtDisplay.setText(txtDisplay.getText() + "8");
        }
        Calculations.numComplete = false;
    }//GEN-LAST:event_btnEightActionPerformed

    //Adds 9 to the display
    private void btnNineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNineActionPerformed
        if (Calculations.numComplete == true) {
            txtDisplay.setText("9");
        } else {
            txtDisplay.setText(txtDisplay.getText() + "9");
        }
        Calculations.numComplete = false;
    }//GEN-LAST:event_btnNineActionPerformed

    //Adds 0 to the displa
    private void btnZeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZeroActionPerformed
        if (Calculations.numComplete == true) {
            txtDisplay.setText("0");
        } else {
            txtDisplay.setText(txtDisplay.getText() + "0");
        }
        Calculations.numComplete = false;
    }//GEN-LAST:event_btnZeroActionPerformed

    //Adds decimal point and produces error message if one already in display
    private void btnPointActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPointActionPerformed
        if (!txtDisplay.getText().contains(".")) {
            if (Calculations.numComplete == true) {
                txtDisplay.setText("0.");
            } else {
                txtDisplay.setText(txtDisplay.getText() + ".");
            }
        } else {
            if (txtDisplay.getText().contains("0.0")) {
                txtDisplay.setText("0.");
            } else {
                errorMessages(3);
            }
        }
        Calculations.numComplete = false;
    }//GEN-LAST:event_btnPointActionPerformed

    //Clears current display but leaves base calculation
    private void btnClearEntryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearEntryActionPerformed
        txtDisplay.setText("0.0");
        Calculations.numComplete = true;
    }//GEN-LAST:event_btnClearEntryActionPerformed

    //Completes required actions when Plus button pushed
    private void btnPlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlusActionPerformed
        try {
            if (Double.parseDouble(txtDisplay.getText()) == 0) {
                throw new ArithmeticException();
            } else {
                txtDisplay.setText(Calculations.plusPushed(txtDisplay.getText()));
            }
        } catch (ArithmeticException ae) {
            errorMessages(1);
        }
    }//GEN-LAST:event_btnPlusActionPerformed

    //Clears display and base calculation
    private void btnClearAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearAllActionPerformed
        Calculations.reset();
        txtDisplay.setText("0.0");
    }//GEN-LAST:event_btnClearAllActionPerformed

    //Completes required actions when Subtract button pushed
    private void btnSubtractActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubtractActionPerformed
        try {
            if (Double.parseDouble(txtDisplay.getText()) == 0) {
                throw new ArithmeticException();
            } else {
                txtDisplay.setText(Calculations.minusPushed(txtDisplay.getText()));
            }
        } catch (ArithmeticException ae) {
            errorMessages(1);
        }
    }//GEN-LAST:event_btnSubtractActionPerformed

    //Completes required actions when Multiply button pushed
    private void btnMultiplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMultiplyActionPerformed
        try {
            if (Double.parseDouble(txtDisplay.getText()) == 0
                    & Calculations.getOperator1() == '/') {
                throw new ArithmeticException();
            } else {
                txtDisplay.setText(Calculations.multiplyPushed(txtDisplay.getText()));
            }
        } catch (ArithmeticException ae) {
            errorMessages(1);
        }
    }//GEN-LAST:event_btnMultiplyActionPerformed

    //Completes required actions when Division button is pushed
    private void btnDivideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDivideActionPerformed
        try {
            if (Double.parseDouble(txtDisplay.getText()) == 0
                    & Calculations.getOperator1() == '/') {
                throw new ArithmeticException();
            } else {
                txtDisplay.setText(Calculations.dividePushed(txtDisplay.getText()));
            }
        } catch (ArithmeticException ae) {
            errorMessages(1);
        }
    }//GEN-LAST:event_btnDivideActionPerformed

    //Completes required actions when Equals button is pushed
    private void btnEqualsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEqualsActionPerformed
        try {
            if (Double.parseDouble(txtDisplay.getText()) == 0
                    & Calculations.getOperator1() == '/') {
                throw new ArithmeticException();
            } else {
                txtDisplay.setText(Calculations.equalsPushed(txtDisplay.getText()));
            }
        } catch (ArithmeticException ae) {
            errorMessages(1);
        }
    }//GEN-LAST:event_btnEqualsActionPerformed
    
    //Sets display to plain text when menu item selected
    private void radPlainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radPlainActionPerformed
        if (radPlain.isSelected()) {
            Font oldFont = txtDisplay.getFont();
            Font newFont = new Font(oldFont.getName(), Font.PLAIN,
                    oldFont.getSize());
            txtDisplay.setFont(newFont);
        }
    }//GEN-LAST:event_radPlainActionPerformed

    //Sets display to be bold text when menu item is selected
    private void radBoldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radBoldActionPerformed
        if (radBold.isSelected()) {
            Font oldFont = txtDisplay.getFont();
            Font newFont = new Font(oldFont.getName(), Font.BOLD, oldFont.getSize());
            txtDisplay.setFont(newFont);
        }
    }//GEN-LAST:event_radBoldActionPerformed

    //Rounds the current display to one decimal place
    private void radOneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radOneActionPerformed
        if (radOne.isSelected()) {
            double value = Double.parseDouble(txtDisplay.getText());
            double result = (double) Math.round(value * 10d) / 10d;
            txtDisplay.setText(Double.toString(result));
            radZero.setSelected(true);
        }
    }//GEN-LAST:event_radOneActionPerformed

    //Rounds current display to 0 decimal places
    private void radZeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radZeroActionPerformed
        if (radZero.isSelected()) {
            double value = Double.parseDouble(txtDisplay.getText());
            double result = (double) Math.round(value * 1d) / 1d;
            txtDisplay.setText(Double.toString(result));
            radZero.setSelected(true);
        }
    }//GEN-LAST:event_radZeroActionPerformed

    //Rounds the current display to 2 decimal places
    private void radTwoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radTwoActionPerformed
        if (radTwo.isSelected()) {
            double value = Double.parseDouble(txtDisplay.getText());
            double result = (double) Math.round(value * 100d) / 100d;
            txtDisplay.setText(Double.toString(result));
            radZero.setSelected(true);
        }
    }//GEN-LAST:event_radTwoActionPerformed

    //Rounds the current display to 3 decimal places
    private void radThreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radThreeActionPerformed
        if (radThree.isSelected()) {
            double value = Double.parseDouble(txtDisplay.getText());
            double result = (double) Math.round(value * 1000d) / 1000d;
            txtDisplay.setText(Double.toString(result));
            radZero.setSelected(true);
        }
    }//GEN-LAST:event_radThreeActionPerformed

    //Rounds the current display to 4 decimal places
    private void radFourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radFourActionPerformed
        if (radFour.isSelected()) {
            double value = Double.parseDouble(txtDisplay.getText());
            double result = (double) Math.round(value * 10000d) / 10000d;
            txtDisplay.setText(Double.toString(result));
            radZero.setSelected(true);
        }
    }//GEN-LAST:event_radFourActionPerformed

    //Rounds the current display to 5 decimal places
    private void radFiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radFiveActionPerformed
        if (radFive.isSelected()) {
            double value = Double.parseDouble(txtDisplay.getText());
            double result = (double) Math.round(value * 100000d) / 100000d;
            txtDisplay.setText(Double.toString(result));
            radZero.setSelected(true);
        }
    }//GEN-LAST:event_radFiveActionPerformed

    //Rounds the current display to 6 decimal places
    private void radSixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radSixActionPerformed
        if (radSix.isSelected()) {
            double value = Double.parseDouble(txtDisplay.getText());
            double result = (double) Math.round(value * 1000000d) / 1000000d;
            txtDisplay.setText(Double.toString(result));
            radZero.setSelected(true);
        }
    }//GEN-LAST:event_radSixActionPerformed

    //Rounds the current display to 7 decimal places
    private void radSevenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radSevenActionPerformed
        if (radSeven.isSelected()) {
            double value = Double.parseDouble(txtDisplay.getText());
            double result = (double) Math.round(value * 10000000d) / 10000000d;
            txtDisplay.setText(Double.toString(result));
            radZero.setSelected(true);
        }
    }//GEN-LAST:event_radSevenActionPerformed

    //Rounds the current display to 8 decimal places
    private void radEightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radEightActionPerformed
        if (radEight.isSelected()) {
            double value = Double.parseDouble(txtDisplay.getText());
            double result = (double) Math.round(value * 100000000d) / 100000000d;
            txtDisplay.setText(Double.toString(result));
            radZero.setSelected(true);
        }
    }//GEN-LAST:event_radEightActionPerformed

    //Rounds the current display to 9 decimal places
    private void radNineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radNineActionPerformed
        if (radNine.isSelected()) {
            double value = Double.parseDouble(txtDisplay.getText());
            double result = (double) Math.round(value * 1000000000d) / 1000000000d;
            txtDisplay.setText(Double.toString(result));
            radZero.setSelected(true);
        }
    }//GEN-LAST:event_radNineActionPerformed

    //Changes current displa from x to 1/x
    private void btnFractionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFractionActionPerformed
        try {
            if (Double.parseDouble(txtDisplay.getText()) == 0) {
                throw new ArithmeticException();
            } else {
                double value = Double.parseDouble(txtDisplay.getText());
                value = 1 / value;
                txtDisplay.setText(Double.toString(value));
            }
        } catch (ArithmeticException ae) {
            errorMessages(1);
        }
    }//GEN-LAST:event_btnFractionActionPerformed

    //Creates the varaible sneccessary to complete power function 
    //at next press of a button
    private void btnToThePowerOfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnToThePowerOfActionPerformed
        txtDisplay.setText(Calculations.powerPushed(txtDisplay.getText()));
    }//GEN-LAST:event_btnToThePowerOfActionPerformed

    //Changes current display value from positive to negative or vice versa
    private void btnPosNegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPosNegActionPerformed
        String display = txtDisplay.getText();
        if (display.charAt(0) == '-') {
            display = display.substring(1);
        } else {
            display = "-" + display;
        }
        txtDisplay.setText(display);
        Calculations.numComplete = true;
    }//GEN-LAST:event_btnPosNegActionPerformed

    //Finds and displays factorial for current display value
    private void btnFactorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFactorialActionPerformed
        try {
            txtDisplay.setText(Calculations.factorial(txtDisplay.getText()));
        } catch (ArithmeticException ae) {
            errorMessages(2);
        }
    }//GEN-LAST:event_btnFactorialActionPerformed

    //Finds sin of current display depending on radian/degrees selection
    private void btnSinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSinActionPerformed
        if (radDegrees.isSelected()) {
            txtDisplay.setText(Calculations.degRadCalc(1, 1, 
                    txtDisplay.getText()));
        } else {
            txtDisplay.setText(Calculations.degRadCalc(1, 2, 
                    txtDisplay.getText()));
        }
    }//GEN-LAST:event_btnSinActionPerformed

    //Finds cos of current display depending on radian/degrees selection
    private void btnCosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCosActionPerformed
        if (radDegrees.isSelected()) {
            txtDisplay.setText(Calculations.degRadCalc(2, 1, 
                    txtDisplay.getText()));
        } else {
            txtDisplay.setText(Calculations.degRadCalc(2, 2, 
                    txtDisplay.getText()));
        }
    }//GEN-LAST:event_btnCosActionPerformed

    //Finds tan of current display depending on radian/degrees selection
    private void btnTanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTanActionPerformed
        if (radDegrees.isSelected()) {
            txtDisplay.setText(Calculations.degRadCalc(3, 1, 
                    txtDisplay.getText()));
        } else {
            txtDisplay.setText(Calculations.degRadCalc(3, 2, 
                    txtDisplay.getText()));
        }
    }//GEN-LAST:event_btnTanActionPerformed

    
    //Finds asin of current display depending on radian/degrees selection
    private void btnAsinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsinActionPerformed
        if (radDegrees.isSelected()) {
            txtDisplay.setText(Calculations.degRadCalc(4, 1, 
                    txtDisplay.getText()));
        } else {
            txtDisplay.setText(Calculations.degRadCalc(4, 2, 
                    txtDisplay.getText()));
        }
    }//GEN-LAST:event_btnAsinActionPerformed

    //Finds acos of current display depending on radian/degrees selection
    private void btnAcosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcosActionPerformed
        if (radDegrees.isSelected()) {
            txtDisplay.setText(Calculations.degRadCalc(5, 1, 
                    txtDisplay.getText()));
        } else {
            txtDisplay.setText(Calculations.degRadCalc(5, 2, 
                    txtDisplay.getText()));
        }
    }//GEN-LAST:event_btnAcosActionPerformed

    //Finds atan of current display depending on radian/degrees selection
    private void btnAtanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtanActionPerformed
        if (radDegrees.isSelected()) {
            txtDisplay.setText(Calculations.degRadCalc(6, 1, 
                    txtDisplay.getText()));
        } else {
            txtDisplay.setText(Calculations.degRadCalc(6, 2, 
                    txtDisplay.getText()));
        }
    }//GEN-LAST:event_btnAtanActionPerformed

    //Displays PI
    private void btnPiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPiActionPerformed
        txtDisplay.setText(String.valueOf(Math.PI));
    }//GEN-LAST:event_btnPiActionPerformed

    private void btnEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEActionPerformed
        txtDisplay.setText(String.valueOf(Math.E));
    }//GEN-LAST:event_btnEActionPerformed

    //Displays E
    private void mnuAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAboutActionPerformed
        pneMessages.showMessageDialog(this, "<HTML>Calculator <br>Created "
                + "BY: Computer Power Plus Student <br>Drew White 92017830"
                + " <br>3/4/17</HTML>", "About", 
                javax.swing.JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_mnuAboutActionPerformed

    //Displays list of Hot Keys when menu item selected
    private void mnuHotKeysActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuHotKeysActionPerformed
        pneMessages.showMessageDialog(this, "<HTML>A - About<br>K - Hot Keys"
                + "<br>Ctrl+P - Plain Font <br>Ctrl+B - Bold Font<br>B - "
                + "Basic view<br>E - Extended view</HTML>", "Hot Keys", 
                javax.swing.JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_mnuHotKeysActionPerformed

    //Displays correct error message when called by another method
    public void errorMessages(int errorMarker) {
        if (errorMarker == 1) {
            pneMessages.showMessageDialog(this, "Division by zero is not "
                    + "allowed.", "Error Message",
                    javax.swing.JOptionPane.INFORMATION_MESSAGE);
            Calculations.reset();
            txtDisplay.setText("0.0");
        } else if (errorMarker == 2) {
            pneMessages.showMessageDialog(this, "ERROR: Please provide a "
                    + "positive integer between 0 and 20", "Value out "
                    + "of range",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
            Calculations.reset();
            txtDisplay.setText("0.0");
        } else if (errorMarker == 3) {
            pneMessages.showMessageDialog(this, "Hey goober, Imma let you "
                    + "finish, but you can't put two decimal points in there!"
                    + " The first decimal point was the greatest decimal "
                    + "point of all time!", "What are you thinking?",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }

    //@param args the command line arguments
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculatorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculatorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculatorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculatorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalculatorFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgrDegRad;
    private javax.swing.ButtonGroup bgrPlainBold;
    private javax.swing.ButtonGroup bgrRounding;
    private javax.swing.JButton btnAcos;
    private javax.swing.JButton btnAsin;
    private javax.swing.JButton btnAtan;
    private javax.swing.JButton btnClearAll;
    private javax.swing.JButton btnClearEntry;
    private javax.swing.JButton btnCos;
    private javax.swing.JButton btnDivide;
    private javax.swing.JButton btnE;
    private javax.swing.JButton btnEight;
    private javax.swing.JButton btnEquals;
    private javax.swing.JButton btnFactorial;
    private javax.swing.JButton btnFive;
    private javax.swing.JButton btnFour;
    private javax.swing.JButton btnFraction;
    private javax.swing.JButton btnMultiply;
    private javax.swing.JButton btnNine;
    private javax.swing.JButton btnOne;
    private javax.swing.JButton btnPi;
    private javax.swing.JButton btnPlus;
    private javax.swing.JButton btnPoint;
    private javax.swing.JButton btnPosNeg;
    private javax.swing.JButton btnSeven;
    private javax.swing.JButton btnSin;
    private javax.swing.JButton btnSix;
    private javax.swing.JButton btnSubtract;
    private javax.swing.JButton btnTan;
    private javax.swing.JButton btnThree;
    private javax.swing.JButton btnToThePowerOf;
    private javax.swing.JButton btnTwo;
    private javax.swing.JButton btnZero;
    private javax.swing.JMenuItem mnuAbout;
    private javax.swing.JMenu mnuFont;
    private javax.swing.JMenu mnuHelp;
    private javax.swing.JMenuItem mnuHotKeys;
    private javax.swing.JMenuBar mnuMenuBar;
    private javax.swing.JMenu mnuRound;
    private javax.swing.JMenu mnuView;
    private javax.swing.JOptionPane pneMessages;
    private javax.swing.JPanel pnlScientific;
    private javax.swing.JRadioButtonMenuItem radBasic;
    private javax.swing.JRadioButtonMenuItem radBold;
    private javax.swing.JRadioButton radDegrees;
    private javax.swing.JRadioButtonMenuItem radEight;
    private javax.swing.JRadioButtonMenuItem radExtended;
    private javax.swing.JRadioButtonMenuItem radFive;
    private javax.swing.JRadioButtonMenuItem radFour;
    private javax.swing.JRadioButtonMenuItem radNine;
    private javax.swing.JRadioButtonMenuItem radOne;
    private javax.swing.JRadioButtonMenuItem radPlain;
    private javax.swing.JRadioButton radRadians;
    private javax.swing.JRadioButtonMenuItem radSeven;
    private javax.swing.JRadioButtonMenuItem radSix;
    private javax.swing.JRadioButtonMenuItem radThree;
    private javax.swing.JRadioButtonMenuItem radTwo;
    private javax.swing.JRadioButtonMenuItem radZero;
    private javax.swing.JTextField txtDisplay;
    // End of variables declaration//GEN-END:variables
}
