/*
 * Import form that allow you to select Location and Flight files to import tot eh Location and Flight tables respectively
 */
package uflybookingsystem;

import java.io.File;
import java.io.InputStream;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;


public class ImportForm extends javax.swing.JFrame {

    MainForm mainform;
    /**
     * Creates new form ImportForm
     * @param mainform
     */
    //InputStream in = null;
    public ImportForm(MainForm mainform) {
        initComponents();
        this.mainform = mainform;
        getContentPane().setBackground(new java.awt.Color(153,204,255));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        jLabel1 = new javax.swing.JLabel();
        txtFlights = new javax.swing.JTextField();
        btnImportFlights = new javax.swing.JButton();
        txtLocations = new javax.swing.JTextField();
        btnImportLocations = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnBrowseFlight = new javax.swing.JButton();
        btnBrowseLocation = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ImportFiles");
        setSize(new java.awt.Dimension(900, 600));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Nyala", 1, 60)); // NOI18N
        jLabel1.setText("Import Files");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(23, 11, 303, 63);

        txtFlights.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtFlights.setName(""); // NOI18N
        getContentPane().add(txtFlights);
        txtFlights.setBounds(20, 390, 363, 21);

        btnImportFlights.setFont(new java.awt.Font("Nyala", 1, 18)); // NOI18N
        btnImportFlights.setText("Import Flights");
        btnImportFlights.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImportFlightsActionPerformed(evt);
            }
        });
        getContentPane().add(btnImportFlights);
        btnImportFlights.setBounds(20, 420, 220, 30);

        txtLocations.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(txtLocations);
        txtLocations.setBounds(20, 130, 363, 21);

        btnImportLocations.setFont(new java.awt.Font("Nyala", 1, 18)); // NOI18N
        btnImportLocations.setText("Import Locations");
        btnImportLocations.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImportLocationsActionPerformed(evt);
            }
        });
        getContentPane().add(btnImportLocations);
        btnImportLocations.setBounds(20, 160, 220, 29);

        btnClose.setFont(new java.awt.Font("Nyala", 1, 18)); // NOI18N
        btnClose.setText("Close");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });
        getContentPane().add(btnClose);
        btnClose.setBounds(250, 470, 130, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Select Locations File:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(23, 110, 114, 15);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Select Flights File:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 370, 97, 15);

        btnBrowseFlight.setFont(new java.awt.Font("Nyala", 1, 18)); // NOI18N
        btnBrowseFlight.setText("Browse");
        btnBrowseFlight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrowseFlightActionPerformed(evt);
            }
        });
        getContentPane().add(btnBrowseFlight);
        btnBrowseFlight.setBounds(250, 420, 130, 30);

        btnBrowseLocation.setFont(new java.awt.Font("Nyala", 1, 18)); // NOI18N
        btnBrowseLocation.setText("Browse");
        btnBrowseLocation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrowseLocationActionPerformed(evt);
            }
        });
        getContentPane().add(btnBrowseLocation);
        btnBrowseLocation.setBounds(250, 160, 130, 30);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uflybookingsystem/Airplaneorange.png"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(450, 90, 400, 386);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //this method allows you to select the Location text file.
    //File's path should appear in the txtLocations 
    private void btnBrowseLocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrowseLocationActionPerformed
       String fileName = browse();
       txtLocations.setText(fileName);
    }//GEN-LAST:event_btnBrowseLocationActionPerformed
    
    //this method allows you to select the Flight text file.
    //File's path should appear in the txtFlights
    private void btnBrowseFlightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrowseFlightActionPerformed
       String fileName = browse();
       txtFlights.setText(fileName);
    }//GEN-LAST:event_btnBrowseFlightActionPerformed

    //Location Import button action. Creates new instance of the LocationImporter
    //and calls it's run() method
    //Then the ImportFeedbackForm instance is created and displayed to see the result of the import
    private void btnImportLocationsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImportLocationsActionPerformed
        String fileName = txtLocations.getText();
        LocationImporter importLocations = new LocationImporter(fileName);
        importLocations.run();
        //System.out.println("Total rows " + importLocations.getResults().getTotalRows());
       
       ImportFeedbackForm feedback = new ImportFeedbackForm(importLocations.getResults());
       feedback.setVisible(true);
    }//GEN-LAST:event_btnImportLocationsActionPerformed

    //Location Import button action. Creates new instance of the LocationImporter
    //and calls it's run() method
    //Then the ImportFeedbackForm instance is created and displayed to see the result of the import
    private void btnImportFlightsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImportFlightsActionPerformed
       FlightImporter importFlights = new FlightImporter(txtFlights.getText());
       importFlights.run();
       ImportFeedbackForm feedback = new ImportFeedbackForm(importFlights.getResults());
       feedback.setVisible(true);
    }//GEN-LAST:event_btnImportFlightsActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
       this.setVisible(false);
       mainform.setVisible(true);
       
    }//GEN-LAST:event_btnCloseActionPerformed

    private String browse(){
        
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Text files", "txt");
        jFileChooser1.setFileFilter(filter);
        int retValue = jFileChooser1.showOpenDialog(null);
        if (retValue == JFileChooser.APPROVE_OPTION){
            File file = jFileChooser1.getSelectedFile();
            String fileName = file.getPath();
            return fileName;
        }
        return null;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ImportForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ImportForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ImportForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ImportForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new ImportForm().setVisible(true);
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBrowseFlight;
    private javax.swing.JButton btnBrowseLocation;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnImportFlights;
    private javax.swing.JButton btnImportLocations;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtFlights;
    private javax.swing.JTextField txtLocations;
    // End of variables declaration//GEN-END:variables
}
