/*
* Form that contains navigation between the other two forms
 */
package uflybookingsystem;

public class MainForm extends javax.swing.JFrame {

    /**
     * Creates new form MainForm
     */

        
    public MainForm() {
        initComponents();
        getContentPane().setBackground(new java.awt.Color(153,204,255));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnImportForm = new javax.swing.JButton();
        btnBookingForm = new javax.swing.JButton();
        lblTitle = new javax.swing.JLabel();
        btnClose = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 204, 0));
        setSize(new java.awt.Dimension(900, 600));
        getContentPane().setLayout(null);

        btnImportForm.setFont(new java.awt.Font("Nyala", 1, 24)); // NOI18N
        btnImportForm.setText("Import Locations and Flights");
        btnImportForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImportFormActionPerformed(evt);
            }
        });
        getContentPane().add(btnImportForm);
        btnImportForm.setBounds(400, 210, 370, 50);

        btnBookingForm.setFont(new java.awt.Font("Nyala", 1, 24)); // NOI18N
        btnBookingForm.setText("Book a Flight");
        btnBookingForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBookingFormActionPerformed(evt);
            }
        });
        getContentPane().add(btnBookingForm);
        btnBookingForm.setBounds(400, 270, 370, 50);

        lblTitle.setFont(new java.awt.Font("Nyala", 1, 60)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("uFly Flight Booking System");
        getContentPane().add(lblTitle);
        lblTitle.setBounds(4, 20, 800, 60);

        btnClose.setFont(new java.awt.Font("Nyala", 1, 24)); // NOI18N
        btnClose.setText("Close");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });
        getContentPane().add(btnClose);
        btnClose.setBounds(640, 390, 130, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uflybookingsystem/Airplaneorange.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 60, 480, 410);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnImportFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImportFormActionPerformed
        ImportForm importForm = new ImportForm(this);
        importForm.setVisible(true);
        importForm.setSize(900, 600);
        importForm.setLocation(250, 250);
        this.setVisible(false);
    }//GEN-LAST:event_btnImportFormActionPerformed

    private void btnBookingFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBookingFormActionPerformed
        BookingForm bookingForm = new BookingForm();
        bookingForm.setVisible(true);
        bookingForm.setSize(900, 600);
        bookingForm.setLocation(250, 250);
        this.setVisible(false);
    }//GEN-LAST:event_btnBookingFormActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCloseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBookingForm;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnImportForm;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables
}
